version: '3.8'

services:
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    ports:
      - "9117:9117"
    networks:
      - multimedia

networks:
  multimedia:
    name: multimedia_network
    external: true 