version: '3.8'

services:
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - ./music:/music
    ports:
      - "8686:8686"
    networks:
      - multimedia

networks:
  multimedia:
    name: multimedia_network
    external: true 