version: '3.8'

services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - LOG_LEVEL=debug
    volumes:
      - ./config:/app/config
    ports:
      - "5055:5055"
    networks:
      - multimedia

networks:
  multimedia:
    name: multimedia_network
    external: true 