version: '3.8'

services:
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
    volumes:
      - /data/transmission/config:/config
      - /home/oicrruf/raspberrypi-multimedia/data/transmission/downloads/complete:/downloads/complete
      - /home/oicrruf/raspberrypi-multimedia/data/transmission/downloads/incomplete:/downloads/incomplete
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    networks:
      - multimedia

networks:
  multimedia:
    name: multimedia_network
    external: true 