version: '3.8'

services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /data/plex/config:/config
      - /data/plex/transcode:/transcode
      - /home/oicrruf/raspberrypi-multimedia/data/transmission/downloads/complete/lidarr:/media/music
      - /home/oicrruf/raspberrypi-multimedia/data/transmission/downloads/complete/sonarr:/media/tv
      - /home/oicrruf/raspberrypi-multimedia/data/transmission/downloads/complete/radarr:/media/movies
    ports:
      - "32400:32400"
      - "3005:3005"
      - "8324:8324"
      - "32469:32469"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    networks:
      - multimedia

networks:
  multimedia:
    name: multimedia_network
    external: true 