version: '3.8'

services:
  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
    ports:
      - "8181:8181"
    networks:
      - multimedia

networks:
  multimedia:
    name: multimedia_network
    external: true 