version: '3.8'

services:
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    ports:
      - "9696:9696"
    networks:
      - multimedia

networks:
  multimedia:
    name: multimedia_network
    external: true 